version: "3.8"
services:
  db:
    image: postgres:15
    container_name: bot1-db-1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: postgres -c 'max_connections=1000' -c 'listen_addresses=*'
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: bot1-pgadmin-1
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - db 